# Server settings (ServerProperties)
logging:
 config: config/logback.xml
 level.*: debug

zookeeper:
 connects: 192.168.5.128:2181
 baseSleepTimeMs: 1000
 maxRetries: 3
 marsRoot: longjiang

host: 192.168.199.123

cluster:
  type: GAME
  name: G1
  number: 1
  useGate: false
  tcpAddress:
   port: 12100
   host: ${host}
  httpAddress:
   port: 8082
   host: ${host}
  rpcAddress:
   port: 12101
   host: ${host}

tcp:
 port: ${cluster.tcpAddress.port}
 host: ${cluster.tcpAddress.host}


server:
 port: ${cluster.httpAddress.port}
 #address: 192.168.2.21
 sessionTimeout: 30
 contextPath: /
 
tomcat:
 accessLogEnabled: false
 protocolHeader: x-forwarded-proto
 remoteIpHeader: x-forwarded-for
 backgroundProcessorDelay: 30 # secs

spring.redis:
  host: 192.168.5.128
  port: 6379
  password: alan
  database: 2

spring.data.mongodb:
      host: 192.168.5.128
      port: 27017
      database: longjiang-game
      username: longjiang
      password: longjiang147
spring:
  kafka:
    bootstrap-servers: 192.168.5.128:9092
    producer:
      client-id: game-1
      retries: 3
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      compression-type: gzip